services:
  - type: web
    name: jacket-app
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    plan: free
    envVars:
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: SECRET_KEY
        sync: false
  - type: worker
    name: jacket-app-scheduler
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduler.py
    autoDeploy: true
    plan: free
    envVars:
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: SECRET_KEY
        sync: false
